[vimdoc-ja]
src.git = "https://github.com/vim-jp/vimdoc-ja"
src.branch = "master"
fetch.github = "vim-jp/vimdoc-ja"

[skkeleton]
src.git = "https://github.com/vim-skk/skkeleton"
src.branch = "main"
fetch.github = "vim-skk/skkeleton"

[cmp-skkeleton]
src.git = "https://github.com/uga-rosa/cmp-skkeleton"
src.branch = "main"
fetch.github = "uga-rosa/cmp-skkeleton"

[hlchunk-nvim]
src.github = "shellRaining/hlchunk.nvim"
src.prefix = "v"
fetch.url = "https://github.com/shellRaining/hlchunk.nvim/archive/refs/tags/v$ver.tar.gz"
