# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cmp-skkeleton = {
    pname = "cmp-skkeleton";
    version = "2c268a407e9e843abd03c6fa77485541a4ddcd9a";
    src = fetchFromGitHub {
      owner = "uga-rosa";
      repo = "cmp-skkeleton";
      rev = "2c268a407e9e843abd03c6fa77485541a4ddcd9a";
      fetchSubmodules = false;
      sha256 = "sha256-Odg0cmLML2L4YVcrMt7Lrie1BAl7aNEq6xqJN3/JhZs=";
    };
    date = "2023-11-26";
  };
  gitmoji-nvim = {
    pname = "gitmoji-nvim";
    version = "3339f97b12e923de77331e09cd427b19139e306f";
    src = fetchFromGitHub {
      owner = "Dynge";
      repo = "gitmoji.nvim";
      rev = "3339f97b12e923de77331e09cd427b19139e306f";
      fetchSubmodules = false;
      sha256 = "sha256-Git7i7OANVQpZ7xK+Uk9zYIdV8RufS3Qarg4KRU/cZE=";
    };
    date = "2026-04-01";
  };
  kotlin-nvim = {
    pname = "kotlin-nvim";
    version = "262340932602a77ce0be12aab949864a37a756bc";
    src = fetchFromGitHub {
      owner = "AlexandrosAlexiou";
      repo = "kotlin.nvim";
      rev = "262340932602a77ce0be12aab949864a37a756bc";
      fetchSubmodules = false;
      sha256 = "sha256-SyYeGwFWCX1zNVV5muzxC6Y3Y6I9V67CNlyEldwj4ck=";
    };
    date = "2026-03-20";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "b530eac5a859ce2f8fa4d99fa5cd83b9d3199086";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "b530eac5a859ce2f8fa4d99fa5cd83b9d3199086";
      fetchSubmodules = false;
      sha256 = "sha256-OhHlG3ngNbvUSNqS/MFJpYI/cfbkxSxTPo8EiSwW/MU=";
    };
    date = "2026-04-02";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "1f75eefd3f19f7c061742bda19f57a41e88c5754";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "1f75eefd3f19f7c061742bda19f57a41e88c5754";
      fetchSubmodules = false;
      sha256 = "sha256-sRTERmfRZCrn1O2vKY1VC9PCL/PiN32tBiYk5G3Fcqw=";
    };
    date = "2026-04-15";
  };
}
