# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cmp-skkeleton = {
    pname = "cmp-skkeleton";
    version = "2c268a407e9e843abd03c6fa77485541a4ddcd9a";
    src = fetchFromGitHub {
      owner = "uga-rosa";
      repo = "cmp-skkeleton";
      rev = "2c268a407e9e843abd03c6fa77485541a4ddcd9a";
      fetchSubmodules = false;
      sha256 = "sha256-Odg0cmLML2L4YVcrMt7Lrie1BAl7aNEq6xqJN3/JhZs=";
    };
    date = "2023-11-26";
  };
  gitmoji-nvim = {
    pname = "gitmoji-nvim";
    version = "2659de229c2b26d50732f1220700eebbcdb2d6ef";
    src = fetchFromGitHub {
      owner = "Dynge";
      repo = "gitmoji.nvim";
      rev = "2659de229c2b26d50732f1220700eebbcdb2d6ef";
      fetchSubmodules = false;
      sha256 = "sha256-cihJ2U+GIqf98t6wS4Fso6R8l69vXT+BsstqY7rrlc4=";
    };
    date = "2025-04-23";
  };
  skkeleton = {
    pname = "skkeleton";
    version = "42b7b62062e5eb4ba157b9e8d12a104777bbd9b3";
    src = fetchFromGitHub {
      owner = "vim-skk";
      repo = "skkeleton";
      rev = "42b7b62062e5eb4ba157b9e8d12a104777bbd9b3";
      fetchSubmodules = false;
      sha256 = "sha256-FqGK4IgD75etYRpdr4NaBHQvlBL5Cx9q0SOy+IoUXoU=";
    };
    date = "2025-09-07";
  };
  vimdoc-ja = {
    pname = "vimdoc-ja";
    version = "752853b9c1ee35a15cc71de53b40e3115fcc91f5";
    src = fetchFromGitHub {
      owner = "vim-jp";
      repo = "vimdoc-ja";
      rev = "752853b9c1ee35a15cc71de53b40e3115fcc91f5";
      fetchSubmodules = false;
      sha256 = "sha256-yiJbNIIIUKOP1c1Dh+h24nexKfQTpltCG6kHyL6j3tQ=";
    };
    date = "2025-09-20";
  };
}
