name: build configurations
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
      - uses: icewind1991/attic-action@5b92b73fc87088f54ee787189f87f57418af3f09 # v1.2.1
        with:
          name: home
          instance: https://attic.taile2777.ts.net/
          authToken: ${{ secrets.ATTIC_TOKEN }}
      - name: GC
        run: |
          df -h
          rm -rf "${AGENT_TOOLSDIRECTORY}"
          df -h
      - name: Build
        run: |
          nix build --no-link --show-trace --system x86_64-linux .
          nix build --no-link --show-trace --system x86_64-linux .#config
          df -h
