name: build configurations
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions: {}
jobs:
  build:
    name: Build packaged neovim
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
      - name: Setup attic client
        run: |
          nix profile install nixpkgs#attic-client
          attic login --set-default home https://attic.taile2777.ts.net "$ATTIC_TOKEN"
          attic use home
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
      - name: GC
        run: |
          df -h
          rm -rf "${AGENT_TOOLSDIRECTORY}"
          df -h
      - name: Build
        run: |
          echo "Building config files"
          nix build --no-link --show-trace .#config
          echo "Building packaged neovim"
          nix build --show-trace .
          df -h
      - name: Push to attic
        if: success()
        run: attic push home ./result
